/**
 * Trust Signal Domain Model — application/domain representation of a Trust Signal.
 *
 * The database (`trust.trust_signals`) is the persistence authority.
 * This model provides a typed, validated domain object that can be used
 * by future Trust Engine tasks (ingestion, scoring, gating) without
 * re-implementing validation or type checks.
 *
 * This is NOT the Trust Signal Ingestion Engine (TRU-003).
 * This is NOT Trust Score Calculation (TRU-004).
 * This is NOT Trust Gating (TRU-007).
 */

import {
  SignalType,
  SignalSource,
  SignalDirection,
  isSignalType,
  isSignalSource,
  isSignalDirection,
  SIGNAL_WEIGHT_MIN,
  SIGNAL_WEIGHT_MAX,
} from './types';

/**
 * A Trust Signal — a typed, validated domain representation of a row in
 * `trust.trust_signals`.
 *
 * Fields mirror the database columns:
 *   - signal_id:       UUID (generated by DB on insert)
 *   - account_id:       UUID — the account this signal belongs to (FK → idm.accounts)
 *   - signal_type:      one of the 17 valid SignalType values
 *   - signal_source:    one of the 7 valid SignalSource values
 *   - signal_direction: POSITIVE | NEGATIVE | NEUTRAL
 *   - signal_value:     JSONB — structured signal payload (engine-specific)
 *   - signal_weight:    DECIMAL(5,4) 0.0000–1.0000 (PROPOSED governance parameter)
 *   - signal_metadata:  JSONB | null — optional metadata
 *   - created_at:       TIMESTAMPTZ — set by DB on insert
 */
export interface TrustSignal {
  signal_id?: string;
  account_id: string;
  signal_type: SignalType;
  signal_source: SignalSource;
  signal_direction: SignalDirection;
  signal_value: Record<string, unknown>;
  signal_weight: number;
  signal_metadata?: Record<string, unknown> | null;
  created_at?: string;
}

/**
 * Validation result for a Trust Signal.
 */
export interface TrustSignalValidationResult {
  valid: boolean;
  errors: string[];
  /** The validated signal, if valid. Null if validation failed. */
  signal: TrustSignal | null;
}

/**
 * Validate a Trust Signal input object.
 *
 * This is server-side/domain validation — authoritative regardless of
 * whether frontend validation ran. Rejects invalid types, sources,
 * directions, weights, and missing required fields.
 *
 * @param input - Partial/raw signal input from any source
 * @returns Validation result with errors array and validated signal (if valid)
 */
export function validateTrustSignal(input: unknown): TrustSignalValidationResult {
  const errors: string[] = [];

  if (input === null || input === undefined || typeof input !== 'object') {
    return { valid: false, errors: ['Signal must be an object.'], signal: null };
  }

  const obj = input as Record<string, unknown>;

  // ── account_id (required, non-empty string) ───────────────────────
  if (!obj.account_id || typeof obj.account_id !== 'string' || obj.account_id.trim() === '') {
    errors.push('account_id is required and must be a non-empty string.');
  }

  // ── signal_type (required, valid enum) ────────────────────────────
  if (!isSignalType(obj.signal_type)) {
    errors.push(
      `signal_type is required and must be one of: TRANSACTION_HISTORY, DISPUTE_HISTORY, CHARGEBACK_HISTORY, FRAUD_FLAGS, SANCTION_HISTORY, ACTIVITY_CONSISTENCY, COMMUNITY_STANDING, VERIFICATION_STATUS, ACCOUNT_AGE, REFERRAL_QUALITY, MARKETPLACE_REVIEWS, MARKETPLACE_RATINGS, MARKETPLACE_DISPUTES, CONTENT_GOVERNANCE, COMPLETION_RATE, RESPONSE_TIME, OTHER.`,
    );
  }

  // ── signal_source (required, valid enum) ──────────────────────────
  if (!isSignalSource(obj.signal_source)) {
    errors.push(
      `signal_source is required and must be one of: COMMERCE, SERVICES, LEARNING, IDENTITY, ADMIN, SYSTEM, WALLET.`,
    );
  }

  // ── signal_direction (required, valid enum) ───────────────────────
  if (!isSignalDirection(obj.signal_direction)) {
    errors.push(
      `signal_direction is required and must be one of: POSITIVE, NEGATIVE, NEUTRAL.`,
    );
  }

  // ── signal_value (required, object) ───────────────────────────────
  if (
    obj.signal_value === null ||
    obj.signal_value === undefined ||
    typeof obj.signal_value !== 'object' ||
    Array.isArray(obj.signal_value)
  ) {
    errors.push('signal_value is required and must be a JSON object.');
  }

  // ── signal_weight (required, number 0–1) ──────────────────────────
  if (typeof obj.signal_weight !== 'number' || Number.isNaN(obj.signal_weight)) {
    errors.push('signal_weight is required and must be a number.');
  } else if (obj.signal_weight < SIGNAL_WEIGHT_MIN || obj.signal_weight > SIGNAL_WEIGHT_MAX) {
    errors.push(
      `signal_weight must be between ${SIGNAL_WEIGHT_MIN} and ${SIGNAL_WEIGHT_MAX}.`,
    );
  }

  // ── signal_metadata (optional, object or null) ─────────────────────
  if (
    obj.signal_metadata !== undefined &&
    obj.signal_metadata !== null &&
    (typeof obj.signal_metadata !== 'object' || Array.isArray(obj.signal_metadata))
  ) {
    errors.push('signal_metadata must be a JSON object or null.');
  }

  if (errors.length > 0) {
    return { valid: false, errors, signal: null };
  }

  // Build the validated signal — fields are now guaranteed valid
  const signal: TrustSignal = {
    account_id: obj.account_id as string,
    signal_type: obj.signal_type as SignalType,
    signal_source: obj.signal_source as SignalSource,
    signal_direction: obj.signal_direction as SignalDirection,
    signal_value: obj.signal_value as Record<string, unknown>,
    signal_weight: obj.signal_weight as number,
    signal_metadata:
      obj.signal_metadata === undefined ? null : (obj.signal_metadata as Record<string, unknown>),
  };

  // Preserve optional fields if present
  if (typeof obj.signal_id === 'string') {
    signal.signal_id = obj.signal_id;
  }
  if (typeof obj.created_at === 'string') {
    signal.created_at = obj.created_at;
  }

  return { valid: true, errors: [], signal };
}

/**
 * Validate only the signal weight value.
 * Matches the database CHECK constraint: 0.0000 <= weight <= 1.0000.
 *
 * @param weight - The weight value to validate
 * @returns true if valid, false otherwise
 */
export function isValidSignalWeight(weight: unknown): boolean {
  if (typeof weight !== 'number' || Number.isNaN(weight)) {
    return false;
  }
  return weight >= SIGNAL_WEIGHT_MIN && weight <= SIGNAL_WEIGHT_MAX;
}
