-- =============================================================================
-- Migration: 000003_create_trust_schema
-- Description: Creates the Trust Engine (trust) schema and foundational tables.
--
--   - trust.trust_records: one per account, current trust state (score, status, tier)
--   - trust.trust_signals: extensible trust signals from across the ecosystem
--   - trust.trust_history: append-only historical trust state changes
--
--   - References idm.accounts (NOT a duplicate identity system)
--   - RLS using auth.uid() (consistent with idm conventions)
--   - Per-table audit triggers (shared.fn_audit_trigger)
--   - trust.fn_set_updated_at() for OCC version + updated_at
--   - Append-only protection on trust_history
--
-- Source: DDD-1 Ch.7 (Trust Engine), SRS-1 SRS-TRU-001..005, KR-1 KR-TRU-001..011
-- Author: K-NETWORK Database Team
-- Date: 2026-08-29
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. CREATE trust SCHEMA
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS trust;

-- =============================================================================
-- 2. HELPER FUNCTIONS
-- =============================================================================

-- trust.fn_set_updated_at() — auto-updates updated_at and increments version (OCC)
-- Consistent with idm.fn_set_updated_at() pattern (DDD-1 Chapter 4.3)
CREATE OR REPLACE FUNCTION trust.fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    IF NEW.version IS NOT NULL THEN
        NEW.version = OLD.version + 1;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- 3. TABLES
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 3.1 trust.trust_records — Current trust state per account (one row per account)
--      References idm.accounts — does NOT duplicate identity.
--      Trust Score is 0–100 (GOVERNANCE PARAMETER per KR-1 KR-TRU-003).
--      Source: SRS-1 SRS-TRU-001, KR-1 KR-TRU-003
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trust.trust_records (
    trust_id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id         UUID NOT NULL,
    trust_score        INTEGER NOT NULL DEFAULT 0
                         CHECK (trust_score >= 0 AND trust_score <= 100),
    trust_status       TEXT NOT NULL DEFAULT 'ACTIVE'
                         CHECK (trust_status IN ('ACTIVE', 'SUSPENDED', 'RECOVERING', 'PROTECTED')),
    trust_tier         TEXT NOT NULL DEFAULT 'UNVERIFIED'
                         CHECK (trust_tier IN ('UNVERIFIED', 'BUILDING', 'ESTABLISHED', 'TRUSTED', 'EXEMPLARY')),
    last_calculated_at TIMESTAMPTZ,
    last_signal_at     TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version            INTEGER NOT NULL DEFAULT 1
);

-- One trust record per account
CREATE UNIQUE INDEX IF NOT EXISTS uq_trust_records_account
    ON trust.trust_records (account_id);

CREATE INDEX IF NOT EXISTS ix_trust_records_score
    ON trust.trust_records (trust_score);

CREATE INDEX IF NOT EXISTS ix_trust_records_status
    ON trust.trust_records (trust_status);

CREATE INDEX IF NOT EXISTS ix_trust_records_tier
    ON trust.trust_records (trust_tier);

-- Triggers
DROP TRIGGER IF EXISTS trg_audit_trust_records ON trust.trust_records;
CREATE TRIGGER trg_audit_trust_records
    AFTER INSERT OR UPDATE OR DELETE ON trust.trust_records
    FOR EACH ROW EXECUTE FUNCTION shared.fn_audit_trigger();

DROP TRIGGER IF EXISTS trg_trust_records_updated_at ON trust.trust_records;
CREATE TRIGGER trg_trust_records_updated_at
    BEFORE UPDATE ON trust.trust_records
    FOR EACH ROW EXECUTE FUNCTION trust.fn_set_updated_at();

-- -----------------------------------------------------------------------------
-- 3.2 trust.trust_signals — Extensible trust signals from across the ecosystem
--      Signals are generated by Commerce, Services, Learning, Identity, Admin.
--      The Trust Engine is the sole owner of trust data (PLC-1 Ch.14).
--      Source: SRS-1 SRS-TRU-001 (multi-signal), SRS-TRU-005 (marketplace signals)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trust.trust_signals (
    signal_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id         UUID NOT NULL,
    signal_type        TEXT NOT NULL CHECK (signal_type IN (
                         'TRANSACTION_HISTORY', 'DISPUTE_HISTORY', 'CHARGEBACK_HISTORY',
                         'FRAUD_FLAGS', 'SANCTION_HISTORY', 'ACTIVITY_CONSISTENCY',
                         'COMMUNITY_STANDING', 'VERIFICATION_STATUS', 'ACCOUNT_AGE',
                         'REFERRAL_QUALITY', 'MARKETPLACE_REVIEWS', 'MARKETPLACE_RATINGS',
                         'MARKETPLACE_DISPUTES', 'CONTENT_GOVERNANCE', 'COMPLETION_RATE',
                         'RESPONSE_TIME', 'OTHER')),
    signal_source      TEXT NOT NULL CHECK (signal_source IN (
                         'COMMERCE', 'SERVICES', 'LEARNING', 'IDENTITY',
                         'ADMIN', 'SYSTEM', 'WALLET')),
    signal_direction   TEXT NOT NULL DEFAULT 'NEUTRAL'
                         CHECK (signal_direction IN ('POSITIVE', 'NEGATIVE', 'NEUTRAL')),
    signal_value       JSONB NOT NULL,
    signal_weight      DECIMAL(5,4) NOT NULL DEFAULT 0.0000
                         CHECK (signal_weight >= 0.0000 AND signal_weight <= 1.0000),
    signal_metadata    JSONB,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_trust_signals_account
    ON trust.trust_signals (account_id);

CREATE INDEX IF NOT EXISTS ix_trust_signals_type
    ON trust.trust_signals (signal_type);

CREATE INDEX IF NOT EXISTS ix_trust_signals_source
    ON trust.trust_signals (signal_source);

CREATE INDEX IF NOT EXISTS ix_trust_signals_created_at
    ON trust.trust_signals (created_at);

-- Composite index for querying signals by account + type
CREATE INDEX IF NOT EXISTS ix_trust_signals_account_type
    ON trust.trust_signals (account_id, signal_type);

-- Trigger
DROP TRIGGER IF EXISTS trg_audit_trust_signals ON trust.trust_signals;
CREATE TRIGGER trg_audit_trust_signals
    AFTER INSERT OR UPDATE OR DELETE ON trust.trust_signals
    FOR EACH ROW EXECUTE FUNCTION shared.fn_audit_trigger();

-- -----------------------------------------------------------------------------
-- 3.3 trust.trust_history — Append-only historical trust state changes
--      History is append-oriented and suitable for auditing (SRS-1 SRS-TRU-001 AC5).
--      UPDATE and DELETE are blocked — corrections via new entries.
--      Source: DDD-1 Ch.7, SRS-1 SRS-TRU-001
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trust.trust_history (
    history_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id         UUID NOT NULL,
    trust_score        INTEGER NOT NULL
                         CHECK (trust_score >= 0 AND trust_score <= 100),
    trust_status       TEXT NOT NULL
                         CHECK (trust_status IN ('ACTIVE', 'SUSPENDED', 'RECOVERING', 'PROTECTED')),
    trust_tier         TEXT NOT NULL
                         CHECK (trust_tier IN ('UNVERIFIED', 'BUILDING', 'ESTABLISHED', 'TRUSTED', 'EXEMPLARY')),
    previous_score     INTEGER
                         CHECK (previous_score IS NULL OR (previous_score >= 0 AND previous_score <= 100)),
    score_delta        INTEGER,
    change_reason      TEXT,
    calculated_by      TEXT NOT NULL DEFAULT 'SYSTEM'
                         CHECK (calculated_by IN ('SYSTEM', 'SCHEDULED', 'EVENT', 'ADMIN')),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_trust_history_account
    ON trust.trust_history (account_id);

CREATE INDEX IF NOT EXISTS ix_trust_history_created_at
    ON trust.trust_history (created_at);

CREATE INDEX IF NOT EXISTS ix_trust_history_account_created
    ON trust.trust_history (account_id, created_at DESC);

-- Audit trigger
DROP TRIGGER IF EXISTS trg_audit_trust_history ON trust.trust_history;
CREATE TRIGGER trg_audit_trust_history
    AFTER INSERT ON trust.trust_history
    FOR EACH ROW EXECUTE FUNCTION shared.fn_audit_trigger();

-- Append-only protection: block UPDATE and DELETE on trust_history
DROP TRIGGER IF EXISTS trg_block_update_trust_history ON trust.trust_history;
CREATE TRIGGER trg_block_update_trust_history
    BEFORE UPDATE ON trust.trust_history
    FOR EACH ROW EXECUTE FUNCTION shared.fn_block_mutation();

DROP TRIGGER IF EXISTS trg_block_delete_trust_history ON trust.trust_history;
CREATE TRIGGER trg_block_delete_trust_history
    BEFORE DELETE ON trust.trust_history
    FOR EACH ROW EXECUTE FUNCTION shared.fn_block_mutation();

-- =============================================================================
-- 4. RLS POLICIES
--    Uses auth.uid() — consistent with idm RLS conventions.
--    Owner can SELECT their own trust data.
--    Writes are server-side only (no direct client writes).
--    Admin role bypasses RLS (BYPASSRLS).
-- =============================================================================

-- 4.1 trust.trust_records — Owner SELECT; server-side writes only
ALTER TABLE trust.trust_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE trust.trust_records FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS trust_records_owner_select ON trust.trust_records;
CREATE POLICY trust_records_owner_select ON trust.trust_records
    FOR SELECT
    USING (account_id = auth.uid());

-- 4.2 trust.trust_signals — Owner SELECT; server-side writes only
ALTER TABLE trust.trust_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE trust.trust_signals FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS trust_signals_owner_select ON trust.trust_signals;
CREATE POLICY trust_signals_owner_select ON trust.trust_signals
    FOR SELECT
    USING (account_id = auth.uid());

-- 4.3 trust.trust_history — Owner SELECT; server-side writes only
ALTER TABLE trust.trust_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE trust.trust_history FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS trust_history_owner_select ON trust.trust_history;
CREATE POLICY trust_history_owner_select ON trust.trust_history
    FOR SELECT
    USING (account_id = auth.uid());

-- =============================================================================
-- 5. GRANTS
-- =============================================================================

GRANT USAGE ON SCHEMA trust TO app_service, readonly_role, admin_role;

-- Supabase-managed roles (authenticated, anon) may not exist in local/dev
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        GRANT USAGE ON SCHEMA trust TO authenticated;
        -- Authenticated users can SELECT their own trust rows (RLS enforces ownership)
        GRANT SELECT ON trust.trust_records TO authenticated;
        GRANT SELECT ON trust.trust_signals TO authenticated;
        GRANT SELECT ON trust.trust_history TO authenticated;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        GRANT USAGE ON SCHEMA trust TO anon;
    END IF;
END $$;

-- Service role gets full DML (server-side operations)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA trust TO app_service;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA trust TO admin_role;

-- Default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA trust
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_service;

-- =============================================================================
-- 6. COMMENTS
-- =============================================================================

COMMENT ON SCHEMA trust IS 'K-NETWORK Trust Engine schema — trust records, signals, and history. Source: DDD-1 Ch.7, SRS-1 SRS-TRU-001..005, KR-1 KR-TRU-001..011.';

COMMENT ON TABLE trust.trust_records IS 'Current trust state per account. One row per account. Trust Score 0–100 (GOVERNANCE PARAMETER). References idm.accounts — does not duplicate identity. Source: SRS-1 SRS-TRU-001, KR-1 KR-TRU-003.';
COMMENT ON TABLE trust.trust_signals IS 'Extensible trust signals from across the ecosystem. Generated by Commerce, Services, Learning, Identity, Admin, System. Source: SRS-1 SRS-TRU-001, SRS-TRU-005.';
COMMENT ON TABLE trust.trust_history IS 'Append-only historical trust state changes. Suitable for auditing. UPDATE/DELETE blocked. Source: DDD-1 Ch.7, SRS-1 SRS-TRU-001.';

COMMENT ON FUNCTION trust.fn_set_updated_at() IS 'Auto-updates updated_at and increments version (OCC). Source: DDD-1 Ch.4.3.';

-- =============================================================================
-- 7. RECORD THIS MIGRATION
-- =============================================================================

INSERT INTO shared.schema_migrations (migration_version, migration_name, checksum)
VALUES ('000003', 'create_trust_schema', 'placeholder-replace-with-sha256')
ON CONFLICT (migration_version) DO NOTHING;

COMMIT;

-- =============================================================================
-- ROLLBACK (DOWN) — Run separately if needed, non-production only
-- =============================================================================
-- BEGIN;
--   DROP TRIGGER IF EXISTS trg_block_delete_trust_history ON trust.trust_history;
--   DROP TRIGGER IF EXISTS trg_block_update_trust_history ON trust.trust_history;
--   DROP TRIGGER IF EXISTS trg_audit_trust_history ON trust.trust_history;
--   DROP TRIGGER IF EXISTS trg_audit_trust_signals ON trust.trust_signals;
--   DROP TRIGGER IF EXISTS trg_trust_records_updated_at ON trust.trust_records;
--   DROP TRIGGER IF EXISTS trg_audit_trust_records ON trust.trust_records;
--   DROP TABLE IF EXISTS trust.trust_history;
--   DROP TABLE IF EXISTS trust.trust_signals;
--   DROP TABLE IF EXISTS trust.trust_records;
--   DROP FUNCTION IF EXISTS trust.fn_set_updated_at();
--   DROP SCHEMA IF EXISTS trust CASCADE;
--   DELETE FROM shared.schema_migrations WHERE migration_version = '000003';
-- COMMIT;
